name: Send Gold Price Email

on:
  schedule:
    # - cron: "0 * * * *" # Runs every hour (at minute 0)
    cron: "* * * * *" # Runs every minute
  workflow_dispatch: # Allows manual execution

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run email scheduler
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SERVICE: ${{ secrets.SERVICE }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
        run: node email-scheduler.js
